# ***TUGAS KELOMPOK METODE NUMERIK EIGEN VALUE APPROXIMATION***
Anggota: Shofwan Fikrul Huda(24060124130106)

Kelas: E
___

#### **A. Definisi**

Nilai Eigen adalah bagian skalar khusus yang memiliki hubungan dengan sistem persamaan linear. Hal ini banyak digunakan dalam persamaan matriks. Eigen value memiliki rumus dasarsebagai berikut:

$Ax = λx$

Angka atau nilai skalar “λ” adalah nilai eigen dari A.

#### **B. Teknik aproksimasi eigen value**

Dalam algoritma eigen value memliki beberapa pendekatan yang dapat dilakukan. di bagian ini, kita akan membahas 4 teknik pendekatan yang dapat dilakukan.

In [165]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**1. Power iteration**

Power iteration adalah pendekatan iteratif yang dapat digunakan untuk menentukan nilai eigen terbesar.

In [166]:
def power_iteration(A, max_iterations=1000, tolerance=1e-6):
    v = np.array(np.ones(A.shape[0]), dtype=float)
    for i in range(max_iterations):
        wi = A @ v
        vi = wi / np.linalg.norm(wi)
        if np.linalg.norm(vi - v) < tolerance:
            break
        v = vi
    eigenvalue = v.T @ A @ v
    return eigenvalue


In [167]:
A = np.array([
    [1, 2, 3, 1, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 3, 7],
    [1, 5, 3, 4, 8],
    [5, 6, 7, 8, 9]
], dtype=float)
eigenvalues = power_iteration(A)
print("Matrix A:\n", A)
print("Eigenvalues of A:\n", eigenvalues)

Matrix A:
 [[1. 2. 3. 1. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 3. 7.]
 [1. 5. 3. 4. 8.]
 [5. 6. 7. 8. 9.]]
Eigenvalues of A:
 24.249542966441247


**2. Transformasi Householder**

Teknik transformasi matriks yang digunakan untuk mereduksi sebuah matriks simetris menjadi bentuk tridiagonal yang serupa (memiliki nilai eigen yang sama). Reduksi ini mempermudah dan mempercepat proses perhitungan nilai eigen menggunakan metode iteratif seperti metode QR. Dengan demikian, metode Householder berfungsi sebagai langkah awal penting dalam aproksimasi nilai eigen, mengoptimalkan efisiensi dan stabilitas komputasi.


In [168]:
def householder(A):
    A = A.copy().astype(float)
    n = A.shape[0]
    for k in range(n - 2):
        x = A[k+1:, k]
        e1 = np.zeros(x.shape)
        e1[0] = 1.0
        v = x + np.sign(x[0]) * np.linalg.norm(x) * e1
        v = v / np.linalg.norm(v)
        I = np.eye(n-k-1)
        H = I - 2.0 * (v[:, None] @ v[None, :])
        Hk = np.eye(n)
        Hk[k+1:, k+1:] = H
        A = Hk @ A @ Hk.T
    return A
        



In [169]:


# Matriks input
A = np.array([
    [1, 2, 3, 1, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 3, 7],
    [1, 5, 3, 4, 8],
    [5, 6, 7, 8, 9]
], dtype=float)
# Format hasil ke 4 desimal (seperti format bank)
print("Hasil matriks A setelah reduksi Householder:")
print(np.round(householder(A), 4))

Hasil matriks A setelah reduksi Householder:
[[ 1.     -6.245   0.     -0.     -0.    ]
 [-6.245  20.0513 -7.5361 -0.      0.    ]
 [ 0.     -7.5361  1.5273  2.1574  0.    ]
 [-0.     -0.      2.1574  0.0951  0.793 ]
 [-0.      0.      0.      0.793  -0.6736]]


**3. QR method**

In [ ]:
def QRmethod(A, max_iter=100, tol=1e-10):
    A = A.copy().astype(float)
    for i in range(max_iter):
        Q, R = np.linalg.qr(A)
        A_next = R @ Q
        if np.linalg.norm(A_next - A) < tol:
            break
        A = A_next

    return np.diag(A)
print("Matriks A:\n")
print(A)
print("Eigenvalues dari A:\n")
print(QRmethod(householder(A)))

Matrix A:

[[1. 2. 3. 1. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 3. 7.]
 [1. 5. 3. 4. 8.]
 [5. 6. 7. 8. 9.]]
Eigenvalues of A:

[24.2495 -3.5779  2.4356 -1.1073 -0.    ]


**4. SVD(Singular Value Decomposition)**

In [174]:
def SVD(A):
    U, S, V = np.linalg.svd(A)
    return S

In [175]:
A = np.array([
    [1, 2, 3, 1, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 3, 7],
    [1, 5, 3, 4, 8],
    [5, 6, 7, 8, 9]
], dtype=float)
print("Matrix A:\n")
print(A)
print("Eigenvalues of A:\n")
print(SVD(A))

Matrix A:

[[1. 2. 3. 1. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 3. 7.]
 [1. 5. 3. 4. 8.]
 [5. 6. 7. 8. 9.]]
Eigenvalues of A:

[24.2495  3.5779  2.4356  1.1073  0.    ]
